### ISSUE TITLE
Add a game version check

### ISSUE THREAD

**Issue by misternebula** [amazingalek/owml#217]
Especially from 1.0.6 -> 1.0.7, if the game is not updated OWML will fail without a clear reason (no errors - maybe that's a separate problem?)
We should have a version defined in the owml manifest (Like mods have a owml version) and check if OWML is trying to run on an old game version. This would have to run before LoadMods, preferably as soon as the first thing OWML does so the code actually has a chance of running before running into version-specific OWML code

**Comment by amazingalek** [comment]
1.0.7 introduced some refactoring (in OW) which made us able to simplify some of the code of OWML. Because of this, OWML is no longer backwards compatible in context of OW versions but I'd say it's definitely worth it, considering code health. I expect people to have up to date OW  especially after the Steam release.

I like your suggestion 👍

**Comment by amazingalek** [comment]
Partly covered by #249

**Comment by Raicuparta** [comment]
@amazingalek We'll probably need a way to check game version before the game starts (which means parsing globalgamemanagers again), so just using Application.Version won't be enough.

**Comment by TAImatem** [comment]
maybe https://github.com/amazingalek/owml/pull/289
