### ISSUE TITLE
Asset loading is a mess

### ISSUE THREAD

**Issue by misternebula** [amazingalek/owml#263]
Loading a texture2d returns... a mesh renderer? WHAT

- Loading a mesh/texture/audio should return only the item being loaded, with no other stuff
- A lot of the code can be simplified as unity has built in methods for loading certain assets

**Comment by misternebula** [comment]
For example, here is the image loading I used for Marshmallow :
![image](https://user-images.githubusercontent.com/41904486/88525300-5434c080-cff2-11ea-99d2-b2e8254c9040.png)

**Comment by misternebula** [comment]
- Meshes : Can still used ObjImporter
- Textures : Can be simplified (see above)
- Audio : Unity has no built in methods for audio loading, so WWW has to be used (or something better?)

**Comment by misternebula** [comment]
Basically I want to try removing the `OnLoaded` stuff that you have to do, and make it just return the wanted asset. However, maybe co-routines are the best option, as they won't hang the program while loading... then again, loading images and meshes should only take a short amount of time (and mods shouldn't really be loading in massive mesh files - that's what asset bundles are for!)

**Comment by amazingalek** [comment]
![image](https://user-images.githubusercontent.com/3322367/88723186-b7c10a00-d128-11ea-896b-65a5e261f7ea.png)

**Comment by amazingalek** [comment]
Good comments 👍 
Some thoughts:

- It's important that loading assets happen in separate threads, as otherwise the game would freeze. Coroutines are one way of doing that.
- Why return textures as part of a gameobject instead of directly? I think I did it that way so the texture would survive when changing scenes - notice the gameobject runs DontDestroyOnLoad().

I agree asset loading deserves an overhaul. We could create an entirely new asset loading project (start from scratch) and deprecate the old one. That'd give us a lot of freedom to re-think it.
